---
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceAroundEqualsInParameterDefault:
  # compatibility with RubyMine defaults (apparently can't override?)
  EnforcedStyle: space

Style/TrailingComma:
  # can't make this only apply to arrays and not params, so it's disabled
  Enabled: false
  #EnforcedStyleForMultiline: comma
